name: Coverage Check

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [PathFilter]
    types: 
      - completed

jobs:
  run:
    name: Coverage Test on CodeCov
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkouts
        uses: actions/checkout@v4

      - name: Setup Ubuntu
        run: |
            sudo apt update -y
            sudo apt install -y tar wget make cmake gcc g++ python3 python3-dev "openmpi-*" libopenmpi-dev
            
      
      - name: Build
        run: /bin/bash mfc.sh build -j $(nproc) --gcov

      - name: Test
        run: /bin/bash mfc.sh test -a -j $(nproc)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

